# Generated by Django 6.0.6 on 2026-07-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('property_type', models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('villa', 'Вилла'), ('office', 'Офис'), ('commercial', 'Коммерческая')], default='apartment', max_length=20, verbose_name='Тип недвижимости')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('area', models.PositiveIntegerField(blank=True, null=True, verbose_name='Площадь')),
                ('rooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Комнаты')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['-created_at'],
            },
        ),
    ]
