# Generated by Django 6.0.6 on 2026-09-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_aicontent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.TextField(blank=True, help_text='Например: парковка, бассейн, терраса, охрана, вид на море.', verbose_name='Особенности и удобства'),
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Санузлы'),
        ),
        migrations.AddField(
            model_name='property',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'Новостройка'), ('excellent', 'Отличное'), ('good', 'Хорошее'), ('needs_repair', 'Требует ремонта')], max_length=20, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='property',
            name='currency',
            field=models.CharField(choices=[('EUR', '€ Евро'), ('USD', '$ Доллар США'), ('RUB', '₽ Рубль')], default='EUR', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='property',
            name='floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='property',
            name='floors_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Этажей в здании'),
        ),
        migrations.AddField(
            model_name='property',
            name='land_area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Площадь участка, м²'),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('reserved', 'Забронирован'), ('sold', 'Продан'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год постройки'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('cottage', 'Дача'), ('land', 'Участок'), ('villa', 'Вилла'), ('office', 'Офис'), ('commercial', 'Коммерческая')], default='apartment', max_length=20, verbose_name='Тип недвижимости'),
        ),
    ]
