# Generated by Django 6.0.6 on 2026-09-13 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_expand_property_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='landing_published',
            field=models.BooleanField(default=False, verbose_name='Лендинг опубликован'),
        ),
        migrations.AddField(
            model_name='property',
            name='landing_slug',
            field=models.SlugField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='landing_template',
            field=models.CharField(choices=[('classic', 'Классический')], default='classic', max_length=30, verbose_name='Шаблон лендинга'),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='properties.property')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RealtorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=150, verbose_name='Имя для лендинга')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('telegram_username', models.CharField(blank=True, max_length=100, verbose_name='Telegram без @')),
                ('whatsapp_phone', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp (номер)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realtor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
