# Generated by Django 6.0.6 on 2026-09-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_add_lead_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtorprofile',
            name='whatsapp_phone',
        ),
        migrations.AddField(
            model_name='realtorprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='realtorprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='realtors/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='realtorprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
    ]
