# Generated by Django 6.0.6 on 2026-09-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_update_realtor_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='landing_template',
            field=models.CharField(choices=[('classic', 'Классический'), ('modern', 'Современный'), ('premium', 'Премиальный')], default='classic', max_length=30, verbose_name='Шаблон лендинга'),
        ),
    ]
