# Generated by Django 6.0.6 on 2026-09-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_add_landing_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Главная фотография'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('showing', 'На показах'), ('reserved', 'Забронирован'), ('sold', 'Продан'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
