# Generated by Django 6.0.6 on 2026-09-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_improve_property_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicontent',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Применён'),
        ),
        migrations.AddField(
            model_name='aicontent',
            name='edited_content',
            field=models.TextField(blank=True, verbose_name='Отредактированный текст'),
        ),
        migrations.AddField(
            model_name='aicontent',
            name='is_applied',
            field=models.BooleanField(default=False, verbose_name='Применён к объекту'),
        ),
        migrations.AddField(
            model_name='aicontent',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='aicontent',
            name='prompt',
            field=models.TextField(blank=True, verbose_name='Запрос к ИИ'),
        ),
        migrations.AddField(
            model_name='aicontent',
            name='provider',
            field=models.CharField(blank=True, max_length=30, verbose_name='Провайдер'),
        ),
        migrations.AddField(
            model_name='aicontent',
            name='tone',
            field=models.CharField(choices=[('business', 'Деловой'), ('premium', 'Премиальный'), ('concise', 'Лаконичный'), ('emotional', 'Эмоциональный')], default='business', max_length=20, verbose_name='Тон'),
        ),
        migrations.AddField(
            model_name='property',
            name='marketing_headline',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок объявления'),
        ),
        migrations.AddField(
            model_name='property',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='aicontent',
            name='content_type',
            field=models.CharField(choices=[('headline', 'Заголовок объявления'), ('short_description', 'Короткое описание'), ('full_description', 'Полное описание'), ('description', 'Описание (архив)')], max_length=30),
        ),
    ]
