# Generated by Django 6.0.6 on 2026-09-17 20:09

import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_aicontent_applied_at_aicontent_edited_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='landing_about_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок блока «Об объекте»'),
        ),
        migrations.AddField(
            model_name='property',
            name='landing_block_order',
            field=models.JSONField(default=properties.models.default_landing_block_order, verbose_name='Порядок блоков лендинга'),
        ),
        migrations.AddField(
            model_name='property',
            name='landing_contact_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок блока заявки'),
        ),
        migrations.AddField(
            model_name='property',
            name='landing_subtitle',
            field=models.TextField(blank=True, verbose_name='Подзаголовок лендинга'),
        ),
        migrations.AddField(
            model_name='property',
            name='landing_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок лендинга'),
        ),
        migrations.AddField(
            model_name='property',
            name='seo_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='SEO-описание'),
        ),
        migrations.AddField(
            model_name='property',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO-заголовок'),
        ),
    ]
