# Generated by Django 6.0.6 on 2026-09-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_property_landing_about_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='avito_export',
            field=models.BooleanField(default=False, verbose_name='Включить в экспорт Avito'),
        ),
        migrations.AddField(
            model_name='property',
            name='avito_operation',
            field=models.CharField(choices=[('sell', 'Продам'), ('rent', 'Сдам')], default='sell', max_length=10, verbose_name='Тип объявления Avito'),
        ),
    ]
