# Generated by Django 6.0.6 on 2026-09-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0014_property_avito_export_property_avito_operation"),
    ]

    operations = [
        migrations.AddField(
            model_name="realtorprofile",
            name="about",
            field=models.TextField(
                blank=True,
                help_text="Коротко расскажите об опыте, подходе к работе или преимуществах. Этот текст появится на лендингах.",
                verbose_name="О риелторе",
            ),
        ),
    ]
