from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from .ai_views import AIAssistantView, AIContentDeleteView, AIContentEditView, AILeadReplyView, generate_description
from .forms import AccountPasswordChangeForm, PhoneAuthenticationForm
from .views import (
    AvitoExportView, CianExportView,
    PropertyCreateView,
    PropertyDetailView,
    PropertyDeleteView,
    PropertyImageUploadView,
    PropertyImagePrimaryView,
    PropertyImageDeleteView,
    PropertyImageReorderView,
    PropertyListView,
    LandingListView,
    PropertyLandingUnpublishView,
    PropertyStatusUpdateView,
    PropertyUpdateView,
    PublicLandingView,
    PropertyLandingPreviewView,
    RealtorProfileUpdateView,
    LeadListView,
    LeadDetailView,
    LeadDeleteView,
    LeadBulkStatusUpdateView,
    ClientListView,
    ClientCreateView,
    ClientDetailView,
    ClientStatusUpdateView,
    ClientInteractionCreateView,
    ClientReminderCreateView,
    ClientReminderCompleteView,
    ClientBulkActionView,
    ClientExportView,
    ClientBoardView,
    register,
)

urlpatterns = [
    path("register/", register, name="register"),
    path("login/", auth_views.LoginView.as_view(authentication_form=PhoneAuthenticationForm), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("profile/", RealtorProfileUpdateView.as_view(), name="edit_profile"),
    path("avito/export/", AvitoExportView.as_view(), name="avito_export"),
    path("cian/export/", CianExportView.as_view(), name="cian_export"),
    path(
        "profile/password/",
        auth_views.PasswordChangeView.as_view(
            form_class=AccountPasswordChangeForm,
            template_name="registration/password_change_form.html",
            success_url=reverse_lazy("edit_profile"),
        ),
        name="password_change",
    ),
    path("leads/", LeadListView.as_view(), name="lead_list"),
    path("leads/bulk-status/", LeadBulkStatusUpdateView.as_view(), name="lead_bulk_status_update"),
    path("leads/<int:pk>/ai-reply/", AILeadReplyView.as_view(), name="lead_ai_reply"),
    path("leads/<int:pk>/", LeadDetailView.as_view(), name="lead_detail"),
    path("leads/<int:pk>/delete/", LeadDeleteView.as_view(), name="lead_delete"),
    path("clients/", ClientListView.as_view(), name="client_list"),
    path("clients/new/", ClientCreateView.as_view(), name="client_create"),
    path("clients/board/", ClientBoardView.as_view(), name="client_board"),
    path("clients/export/", ClientExportView.as_view(), name="client_export"),
    path("clients/bulk/", ClientBulkActionView.as_view(), name="client_bulk_action"),
    path("clients/<int:pk>/", ClientDetailView.as_view(), name="client_detail"),
    path("clients/<int:pk>/status/", ClientStatusUpdateView.as_view(), name="client_status_update"),
    path("clients/<int:pk>/interactions/", ClientInteractionCreateView.as_view(), name="client_interaction_create"),
    path("clients/<int:pk>/reminders/", ClientReminderCreateView.as_view(), name="client_reminder_create"),
    path("clients/<int:pk>/reminders/<int:reminder_pk>/complete/", ClientReminderCompleteView.as_view(), name="client_reminder_complete"),
    path("landings/", LandingListView.as_view(), name="landing_list"),
    path("landings/<int:pk>/unpublish/", PropertyLandingUnpublishView.as_view(), name="landing_unpublish"),
    path("", PropertyListView.as_view(), name="property_list"),
    path("landing/<slug:slug>/", PublicLandingView.as_view(), name="public_landing"),
    path("create/", PropertyCreateView.as_view(), name="create_property"),
    path("<int:pk>/edit/", PropertyUpdateView.as_view(), name="edit_property"),
    path("<int:pk>/delete/", PropertyDeleteView.as_view(), name="delete_property"),
    path("<int:pk>/status/", PropertyStatusUpdateView.as_view(), name="update_property_status"),
    path("<int:pk>/ai/", AIAssistantView.as_view(), name="ai_assistant"),
    path("<int:pk>/landing-preview/", PropertyLandingPreviewView.as_view(), name="property_landing_preview"),
    path("<int:pk>/", PropertyDetailView.as_view(), name="property_detail"),
    path("<int:pk>/generate/", generate_description, name="generate_description"),
    path("ai/content/<int:pk>/", AIContentEditView.as_view(), name="ai_content_edit"),
    path("ai/content/<int:pk>/delete/", AIContentDeleteView.as_view(), name="ai_content_delete"),
    path("<int:pk>/images/", PropertyImageUploadView.as_view(), name="upload_images"),
    path("<int:pk>/images/reorder/", PropertyImageReorderView.as_view(), name="reorder_images"),
    path("<int:pk>/images/<int:image_pk>/primary/", PropertyImagePrimaryView.as_view(), name="set_primary_image"),
    path("<int:pk>/images/<int:image_pk>/delete/", PropertyImageDeleteView.as_view(), name="delete_property_image"),
]
