from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from .ai_views import AIAssistantView, AIBundleGenerateView, AIContentDeleteView, AIContentEditView, AIInlineGenerateView, AILeadReplyView, generate_description
from .forms import AccountPasswordChangeForm, PhoneAuthenticationForm
from .deal_views import DealBoardView, DealCreateView, DealUpdateView
from .agency_views import (
    AgencyCreateView, AgencyDashboardView, AgencyInviteView, AgencyInviteRevokeView, AgencyJoinView,
    AgencyMemberRemoveView, AgencyMemberRoleView, LeadAssignView,
)
from .workday_views import (
    ShowingCreateView, ShowingUpdateView, TaskCompleteView, TaskCreateView, TaskUpdateView, WorkdayView,
)
from .views import (
    AvitoExportView, CianExportView, PropertyPresentationPDFView, PropertyPresentationDOCXView,
    PropertyCreateView,
    PropertyDetailView,
    PropertyDeleteView,
    PropertyImageUploadView,
    PropertyImagePrimaryView,
    PropertyImageDeleteView,
    PropertyImageReorderView,
    PropertyListView,
    LandingListView,
    PropertyLandingUnpublishView,
    PropertyStatusUpdateView,
    PropertyUpdateView,
    PublicLandingView,
    PropertyLandingPreviewView,
    RealtorProfileUpdateView,
    LeadListView,
    LeadDetailView,
    LeadDeleteView,
    LeadBulkStatusUpdateView,
    ClientListView,
    ClientCreateView,
    ClientDetailView,
    ClientStatusUpdateView,
    ClientInteractionCreateView,
    ClientReminderCreateView,
    ClientReminderCompleteView,
    ClientBulkActionView,
    ClientExportView,
    ClientBoardView,
    DemoDataCreateView,
    OnboardingDismissView,
    OnboardingStartManualView,
    personal_data_consent,
    privacy_policy,
    register,
    service_terms,
)

urlpatterns = [
    path("legal/privacy-policy/", privacy_policy, name="privacy_policy"),
    path("legal/personal-data-consent/", personal_data_consent, name="personal_data_consent"),
    path("legal/terms/", service_terms, name="service_terms"),
    path("register/", register, name="register"),
    path("onboarding/demo/", DemoDataCreateView.as_view(), name="onboarding_demo_create"),
    path("onboarding/create-object/", OnboardingStartManualView.as_view(), name="onboarding_start_manual"),
    path("onboarding/dismiss/", OnboardingDismissView.as_view(), name="onboarding_dismiss"),
    path("login/", auth_views.LoginView.as_view(authentication_form=PhoneAuthenticationForm), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("profile/", RealtorProfileUpdateView.as_view(), name="edit_profile"),
    path("agency/", AgencyDashboardView.as_view(), name="agency_dashboard"),
    path("agency/create/", AgencyCreateView.as_view(), name="agency_create"),
    path("agency/invite/", AgencyInviteView.as_view(), name="agency_invite"),
    path("agency/invitations/<int:pk>/revoke/", AgencyInviteRevokeView.as_view(), name="agency_invite_revoke"),
    path("agency/join/<uuid:code>/", AgencyJoinView.as_view(), name="agency_join"),
    path("agency/members/<int:pk>/role/", AgencyMemberRoleView.as_view(), name="agency_member_role"),
    path("agency/members/<int:pk>/remove/", AgencyMemberRemoveView.as_view(), name="agency_member_remove"),
    path("avito/export/", AvitoExportView.as_view(), name="avito_export"),
    path("cian/export/", CianExportView.as_view(), name="cian_export"),
    path(
        "profile/password/",
        auth_views.PasswordChangeView.as_view(
            form_class=AccountPasswordChangeForm,
            template_name="properties/password_change_form.html",
            success_url=reverse_lazy("edit_profile"),
        ),
        name="password_change",
    ),
    path("leads/", LeadListView.as_view(), name="lead_list"),
    path("leads/bulk-status/", LeadBulkStatusUpdateView.as_view(), name="lead_bulk_status_update"),
    path("leads/<int:pk>/ai-reply/", AILeadReplyView.as_view(), name="lead_ai_reply"),
    path("leads/<int:pk>/assign/", LeadAssignView.as_view(), name="lead_assign"),
    path("leads/<int:pk>/", LeadDetailView.as_view(), name="lead_detail"),
    path("leads/<int:pk>/delete/", LeadDeleteView.as_view(), name="lead_delete"),
    path("clients/", ClientListView.as_view(), name="client_list"),
    path("clients/new/", ClientCreateView.as_view(), name="client_create"),
    path("clients/board/", ClientBoardView.as_view(), name="client_board"),
    path("clients/export/", ClientExportView.as_view(), name="client_export"),
    path("clients/bulk/", ClientBulkActionView.as_view(), name="client_bulk_action"),
    path("clients/<int:pk>/", ClientDetailView.as_view(), name="client_detail"),
    path("clients/<int:pk>/status/", ClientStatusUpdateView.as_view(), name="client_status_update"),
    path("clients/<int:pk>/interactions/", ClientInteractionCreateView.as_view(), name="client_interaction_create"),
    path("clients/<int:pk>/reminders/", ClientReminderCreateView.as_view(), name="client_reminder_create"),
    path("clients/<int:pk>/reminders/<int:reminder_pk>/complete/", ClientReminderCompleteView.as_view(), name="client_reminder_complete"),
    path("deals/", DealBoardView.as_view(), name="deal_board"),
    path("deals/new/", DealCreateView.as_view(), name="deal_create"),
    path("deals/<int:pk>/", DealUpdateView.as_view(), name="deal_detail"),
    path("today/", WorkdayView.as_view(), name="workday"),
    path("tasks/new/", TaskCreateView.as_view(), name="task_create"),
    path("tasks/<int:pk>/", TaskUpdateView.as_view(), name="task_detail"),
    path("tasks/<int:pk>/complete/", TaskCompleteView.as_view(), name="task_complete"),
    path("showings/new/", ShowingCreateView.as_view(), name="showing_create"),
    path("showings/<int:pk>/", ShowingUpdateView.as_view(), name="showing_detail"),
    path("landings/", LandingListView.as_view(), name="landing_list"),
    path("landings/<int:pk>/unpublish/", PropertyLandingUnpublishView.as_view(), name="landing_unpublish"),
    path("", PropertyListView.as_view(), name="property_list"),
    path("landing/<slug:slug>/", PublicLandingView.as_view(), name="public_landing"),
    path("create/", PropertyCreateView.as_view(), name="create_property"),
    path("<int:pk>/edit/", PropertyUpdateView.as_view(), name="edit_property"),
    path("<int:pk>/delete/", PropertyDeleteView.as_view(), name="delete_property"),
    path("<int:pk>/status/", PropertyStatusUpdateView.as_view(), name="update_property_status"),
    path("<int:pk>/ai/", AIAssistantView.as_view(), name="ai_assistant"),
    path("<int:pk>/ai/inline/", AIInlineGenerateView.as_view(), name="ai_inline_generate"),
    path("<int:pk>/ai/bundle/", AIBundleGenerateView.as_view(), name="ai_bundle_generate"),
    path("<int:pk>/landing-preview/", PropertyLandingPreviewView.as_view(), name="property_landing_preview"),
    path("<int:pk>/presentation.pdf", PropertyPresentationPDFView.as_view(), name="property_presentation_pdf"),
    path("<int:pk>/presentation.docx", PropertyPresentationDOCXView.as_view(), name="property_presentation_docx"),
    path("<int:pk>/", PropertyDetailView.as_view(), name="property_detail"),
    path("<int:pk>/generate/", generate_description, name="generate_description"),
    path("ai/content/<int:pk>/", AIContentEditView.as_view(), name="ai_content_edit"),
    path("ai/content/<int:pk>/delete/", AIContentDeleteView.as_view(), name="ai_content_delete"),
    path("<int:pk>/images/", PropertyImageUploadView.as_view(), name="upload_images"),
    path("<int:pk>/images/reorder/", PropertyImageReorderView.as_view(), name="reorder_images"),
    path("<int:pk>/images/<int:image_pk>/primary/", PropertyImagePrimaryView.as_view(), name="set_primary_image"),
    path("<int:pk>/images/<int:image_pk>/delete/", PropertyImageDeleteView.as_view(), name="delete_property_image"),
]
